[build-system]
requires = [
  "setuptools >= 42.0.2",  # required by pyproject+setuptools_scm integration
  "setuptools_scm >= 1.15.0",
  "setuptools_scm_git_archive >= 1.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
