---
{% raw -%}
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    ssh_port: 22

    security_group_name: molecule
    security_group_description: "Security group for testing Molecule"
    security_group_rules:
      - proto: tcp
        port: "{{ ssh_port }}"
        cidr: '0.0.0.0/0'
      - proto: icmp
        port: -1
        cidr: '0.0.0.0/0'
      - ethertype: IPv4
        group: "{{ security_group.id }}"
      - ethertype: IPv6
        group: "{{ security_group.id }}"

    key_pair_name: "key-pair-{{ molecule_yml['platforms'][0]['name'] }}"
    key_pair_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
  tasks:
    - name: Create security group
      os_security_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
      register: security_group

    - name: Create security group rules
      os_security_group_rule:
        security_group: "{{ security_group_name }}"
        protocol: "{{ item.proto | default(omit) }}"
        port_range_min: "{{ item.port | default(omit) }}"
        port_range_max: "{{ item.port | default(omit) }}"
        remote_ip_prefix: "{{ item.cidr | default(omit) }}"
        remote_group: "{{ item.group | default(omit) }}"
        ethertype: "{{ item.ethertype | default(omit) }}"
      loop: "{{ security_group_rules }}"

    - name: Test for presence of local key pair
      stat:
        path: "{{ key_pair_path }}"
      register: key_pair_local

    - name: Delete remote key pair
      os_keypair:
        name: "{{ key_pair_name }}"
        state: absent
      when: not key_pair_local.stat.exists

    - name: Create key pair
      os_keypair:
        name: "{{ key_pair_name }}"
      register: key_pair

    - name: Persist the key pair
      copy:
        dest: "{{ key_pair_path }}"
        content: "{{ key_pair.key.private_key }}"
        mode: 0600
      when: key_pair.changed

    - name: Create molecule instance(s)
      os_server:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        flavor: "{{ item.flavor }}"
        security_groups: "{{ security_group_name }}"
        key_name: "{{ key_pair_name }}"
        network: "{{ item.network }}"
        floating_ip_pools: "{{ item.fip_pool | default(omit) }}"
        meta:
          ssh_user: "{{ item.ssh_user }}"
      register: server
      loop: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: os_jobs
      until: os_jobs.finished
      retries: 300
      loop: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.openstack.name }}",
          'instance_id': "{{ item.openstack.id }}",
          'address': "{{ item.openstack.accessIPv4 }}",
          'user': "{{ item.openstack.metadata.ssh_user }}",
          'port': "{{ ssh_port }}",
          'identity_file': "{{ keypair_path }}", }
      loop: "{{ os_jobs.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool

    - name: Wait for SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 10
      loop: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
{%- endraw %}
